version: "3"

services:

  activemq:
    image: webcenter/activemq
    environment:
      - DEBUG=1
      - ACTIVEMQ_CONFIG_NAME=amqp-srv1
      - ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=ezmoney
      - ACTIVEMQ_USERS_tracktik=ezmoney
      - ACTIVEMQ_GROUPS_writes=ezmoney
      - ACTIVEMQ_GROUPS_reads=ezmoney
      - ACTIVEMQ_JMX_jmx1_role=readwrite
      - ACTIVEMQ_JMX_jmx1_password=ezmoney
      - ACTIVEMQ_JMX_jmx2_role=read
      - ACTIVEMQ_JMX_jmx2_password=ezmoney
      - ACTIVEMQ_CONFIG_QUEUES_queue1=schedule.request
      - ACTIVEMQ_CONFIG_QUEUES_queue2=schedule.response
      - ACTIVEMQ_CONFIG_MINMEMORY=1024
      - ACTIVEMQ_CONFIG_MAXMEMORY=4096
      - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
    ports:
      - 127.0.0.1:8161:8161
      - 127.0.0.1:61616:61616
      - 127.0.0.1:61613:61613
    volumes:
      - activemq_data:/data

volumes:
  activemq_data:
